### ISSUE TITLE
3D print files 404

### ISSUE THREAD

**Issue by eddielee6** [TrashRobotics/LaserCatToy#1]
Hey. Would love to have a go building this, but the files on thingiverse give a 404 when downloading.

Thanks

**Comment by TrashRobotics** [comment]
Hi, try to download files not through "Download All", but one file at a time. I suspect there is a problem with thingiverse. I previously tried to re-upload files there, but nothing worked. I'll try again later. maybe they have already fixed this.

**Comment by TrashRobotics** [comment]
> Hey. Would love to have a go building this, but the files on thingiverse give a 404 when downloading.
> 
> Thanks

Hi, try to download files not through "Download All", but one file at a time. I suspect there is a problem with thingiverse. I previously tried to re-upload files there, but nothing worked. I'll try again later. maybe they have already fixed this.

**Comment by eddielee6** [comment]
Ah perfect this works! Thank you!!
